### ISSUE TITLE
/Register como voluntario

### ISSUE THREAD

**Issue by FluxFeint** [4GeeksAcademy/GenBridge#5]
Front

Crear form que contega:

Una barra para el nombre

Una barra para el apellido

Una barra para el nombre de usuario

Una barra para la contraseña

Una barra para el repite contraseña

El sign up botón

End

Crear Route Method Post

Crear Modelo

Linkear Sign up boton con Back END

**Comment by JuanPenalver11** [comment]
Front 

Crear form que contega: 

Una barra para el nombre 

Una barra para el apellido 

Una barra para el nombre de usuario 

Una barra para la contraseña 

Una barra para el repite contraseña 

El sign up botón 

End 

Crear Route Method Post 

Crear Modelo 

Linkear Sign up boton con Back END
